export default [
    {
        id: 1,
        person: 'Oprah Winfrey',
        image: require('../assets/images/achivePersonalities/pers1.png'),
        text: 'From Poverty to Global Fame',
        fullText: 'Oprah was born into a poor family, endured a difficult childhood, and suffered abuse. Despite this, she never gave up and used education and perseverance as her keys to success. Starting her career in television, she became the first Black woman to host her own talk show, later becoming a billionaire and one of the most influential women in the world.',
    },
    {
        id: 2,
        person: 'Jack Ma',
        image: require('../assets/images/achivePersonalities/pers2.png'),
        text: 'From Hundreds of Rejections to Creating Alibaba',
        fullText: 'The future founder of Alibaba failed his university entrance exams multiple times and was rejected by dozens of companies, including KFC. But Jack didn’t give up. Instead, he started an internet-based business in China when few even knew about digital technology. Today, Alibaba is one of the largest online companies in the world.',
    },
    {
        id: 3,
        person: 'Stephen King',
        image: require('../assets/images/achivePersonalities/pers3.png'),
        text: '30 Rejections Before Becoming a Legendary Writer',
        fullText: 'King wrote Carrie, but received 30 rejection letters from publishers. Discouraged, he threw the manuscript away, but his wife convinced him to keep trying. Eventually, the book became a bestseller, launching King’s legendary career. His stories continue to inspire millions worldwide.',
    },
    {
        id: 4,
        person: 'Thomas Edison',
        image: require('../assets/images/achivePersonalities/pers4.png'),
        text: '10,000 Failures Before a Groundbreaking Invention',
        fullText: 'While developing the lightbulb, Edison failed over 10,000 times. But he believed that each failure was just another step forward. His persistence led to one of the most significant inventions in human history.',
    },
    {
        id: 5,
        person: 'Walt Disney',
        image: require('../assets/images/achivePersonalities/pers5.png'),
        text: 'Fired for “Lack of Creativity,” Then Built an Empire',
        fullText: 'Disney was fired from a newspaper for “not being creative enough.” He then experienced several business failures before creating Mickey Mouse. Today, his name is synonymous with magic, childhood, and some of the most beloved animated films of all time.',
    },
    {
        id: 6,
        person: 'Jim Carrey',
        image: require('../assets/images/achivePersonalities/pers6.png'),
        text: 'From Homelessness to Hollywood Stardom',
        fullText: 'As a teenager, Jim Carrey’s family lived in their car, and he worked as a janitor. But he believed in his talent, wrote himself checks for millions of dollars, and one day, he actually earned them. He became one of the most successful comedians and actors in film history.',
    },
    {
        id: 7,
        person: 'J.K. Rowling',
        image: require('../assets/images/achivePersonalities/pers7.png'),
        text: 'From Poverty to a Global Literary Phenomenon',
        fullText: 'Rowling was a struggling single mother living on welfare when she wrote Harry Potter. Her book was rejected by 12 publishers, but she never gave up. Eventually, her story became a cultural phenomenon, and she became one of the most successful authors in the world.',
    },
    {
        id: 8,
        person: 'Michael Jordan',
        image: require('../assets/images/achivePersonalities/pers8.png'),
        text: 'Cut from His Team, But Became a Legend',
        fullText: 'As a teenager, Jordan didn’t make his high school basketball team. Instead of giving up, he trained even harder. He went on to become a six-time NBA champion and one of the greatest athletes of all time.',
    },
    {
        id: 9,
        person: 'Nelson Mandela',
        image: require('../assets/images/achivePersonalities/pers9.png'),
        text: '27 Years in Prison and a Triumph for Freedom',
        fullText: 'Mandela spent 27 years in prison for fighting against apartheid. Instead of seeking revenge, he chose forgiveness and dialogue, becoming South Africa’s first Black president and a global symbol of peace and freedom.',
    },
    {
        id: 10,
        person: 'Arianna Huffington',
        image: require('../assets/images/achivePersonalities/pers10.png'),
        text: '36 Rejections Before Creating a Media Empire',
        fullText: 'When Arianna tried to publish her first book, she was rejected by 36 publishers. Instead of giving up, she founded The Huffington Post, which became one of the world’s most popular news platforms.',
    },
];