export default [
    {
        id: 1,
        person: 'The 5-Second Rule',
        image: require('../assets/images/applyImages/applyImage1.png'),
        text: 'If you’re struggling to make a decision, count 5-4-3-2-1 and just do it',
        fullText: 'This method was developed by Mel Robbins. It helps eliminate analysis paralysis and fear of action. When you need to do something but hesitate, start counting: 5-4-3-2-1 – and immediately act. It works because your brain doesn’t have time to doubt, and you move into action right away.\n\nHow to apply it:\n• Can’t get out of bed in the morning? Count and get up.\n• Nervous about talking to a stranger? Count and speak.\n• Procrastinating on an important task? Count and begin.',
    },
    {
        id: 2,
        person: 'The “2-Minute Rule”',
        image: require('../assets/images/applyImages/applyImage2.png'),
        text: 'If a task takes less than 2 minutes, do it immediately',
        fullText: 'This technique is part of the Getting Things Done system by David Allen. Its essence is simple: if something takes less than 2 minutes, don’t delay it.\n\nHow to apply it:\n• Answer a short email immediately.\n• Wash the dish right after eating.\n• Make a quick note of a task if you can’t do it right now.\nThis approach prevents small tasks from piling up and becoming overwhelming.',
    },
    {
        id: 3,
        person: 'The 80/20 Rule',
        image: require('../assets/images/applyImages/applyImage3.png'),
        text: '20% of actions bring 80% of results, focus on what matters',
        fullText: 'This principle was introduced by economist Vilfredo Pareto. It states that 20% of efforts lead to 80% of results.\n\nHow to apply it:\n• Identify the 20% of tasks that bring you the most value and focus on them.\n• At work, prioritize the key tasks, not small ones.\n• In business, focus on the most profitable clients and products.',
    },
    {
        id: 4,
        person: 'The 1% Rule',
        image: require('../assets/images/applyImages/applyImage4.png'),
        text: 'Improve something by 1% every day, and the results will be huge over a year',
        fullText: 'In Atomic Habits by James Clear, it’s explained that if you improve by 1% each day, by the end of the year, you’ll have improved more than 37 times!\n\nHow to apply it:\n• Practice a skill for just 5-10 minutes daily.\n• Read 1 extra page each day.\n• Add one small productive habit each week.',
    },
    {
        id: 5,
        person: 'Morning Routine',
        image: require('../assets/images/applyImages/applyImage5.png'),
        text: 'Start your day with gratitude, exercise, and planning',
        fullText: 'As your morning begins, so goes the rest of your day. Make it a habit to start your day right.\n\nHow to apply it:\n• Write down 3 things you’re grateful for.\n• Do a quick workout or stretching.\n• Plan your top 3 tasks for the day.',
    },
    {
        id: 6,
        person: 'Try Something New',
        image: require('../assets/images/applyImages/applyImage6.png'),
        text: 'Once a week, do something new to boost your thinking',
        fullText: 'Trying new things stimulates your brain to create new neural connections. This boosts creativity and helps you adapt to change.\n\nHow to apply it:\n• Take a new route to work.\n• Try a new dish at a restaurant.\n• Learn a new skill, even if it’s small.',
    },
    {
        id: 7,
        person: 'Victory Journal',
        image: require('../assets/images/applyImages/applyImage7.png'),
        text: 'Write down 3 achievements of the day to build confidence',
        fullText: 'Writing down your accomplishments, no matter how small, trains your brain to focus on success.\n\nHow to apply it:\n• At the end of the day, write down 3 things you achieved.\n• Even if the day was tough, find at least one success.\n• Over time, you’ll see how much you’ve already accomplished.',
    },
    {
        id: 8,
        person: 'The “No Screens Before Bed” Rule',
        image: require('../assets/images/applyImages/applyImage8.png'),
        text: 'Reduces stress and improves sleep',
        fullText: 'The blue light from screens interferes with melatonin production, the sleep hormone.\n\nHow to apply it:\n• Turn off gadgets 30-60 minutes before bed.\n• Read a book or keep a journal before sleep.\n• Use your phone’s “night mode” if you need to keep it on.',
    },
    {
        id: 9,
        person: 'Small Steps',
        image: require('../assets/images/applyImages/applyImage9.png'),
        text: 'Don’t wait for the perfect moment, start with something small',
        fullText: 'Many people don’t start important tasks because they’re waiting for the perfect moment. But the perfect moment is now.\n\nHow to apply it:\n• Want to write a book? Start with one page.\n• Want to run? Just go for a walk.\n• The most important thing is to start, even with the smallest step.',
    },
    {
        id: 10,
        person: 'The Art of Saying “No”',
        image: require('../assets/images/applyImages/applyImage10.png'),
        text: 'Learn to refuse unnecessary tasks to focus on what matters',
        fullText: 'If you constantly say “yes” to unnecessary things, you won’t have time for what’s important.\n\nHow to apply it:\n• Evaluate whether the task is really necessary.\n• Learn to say “no” politely but firmly.\n• Protect your time and energy.',
    },
];